name: PatreonPlugin
version: 0.1
main: com.brandongcobb.patreon.PatreonPlugin
api-version: 1.0
website: www.github.com/brandongrahamcobb
commands:
  code:
    usage: /code
    description:
  discord:
    usage: /discord
    description:
  patreon:
    usage: /patreon
    description:
